<?php
declare(strict_types=1);
use App\Domain\Career\Career; use App\Domain\Season\Season; use App\Domain\Squad\SquadPlayer; use Yiisoft\Html\Html; use Yiisoft\Yii\View\Renderer\Csrf;
/** @var Career $career */ /** @var Season $season */ /** @var string|null $clubLogoUrl */ /** @var list<SquadPlayer> $players */ /** @var Csrf $csrf */
$this->setTitle('Squad · ' . $career->name->value); $positions = ['GK','LB','LWB','CB','RB','RWB','CDM','CM','CAM','LM','RM','LW','LF','CF','RF','RW','ST'];
?>
<section class="squad-page" data-squad-page>
<a class="career-dashboard__back" href="<?= Html::encode($urlGenerator->generate('career.dashboard', ['id' => $career->id->toString()])) ?>">← <?= Html::encode($career->name->value) ?></a>
<header class="squad-page__header"><div class="squad-page__identity"><?php if ($clubLogoUrl !== null): ?><img src="<?= Html::encode($clubLogoUrl) ?>" alt=""><?php endif ?><div><p class="eyebrow"><?= Html::encode($season->label->value) ?></p><h1>Squad</h1><p><?= Html::encode($career->name->value) ?> · <?= Html::encode($season->managedClub->name) ?> · <span data-squad-count><?= count($players) ?></span> players</p></div></div><p class="squad-page__hint">Edit any cell. Changes save when you leave it. The final row is always ready for a new player.</p></header>
<p class="squad-page__status" data-squad-status role="status" aria-live="polite"></p>
<form id="new-squad-player" method="post" action="<?= Html::encode($urlGenerator->generate('career.squad.store', ['id' => $career->id->toString()])) ?>" data-new-squad-player><?= $csrf->hiddenInput()->render() ?></form>
<div class="squad-table-wrap"><table class="squad-table squad-table--editor" data-squad-table><thead><tr><th><button type="button" data-sort="position">Position</button></th><th><button type="button" data-sort="name">Player</button></th><th><button type="button" data-sort="birth_date">Age</button></th><th><button type="button" data-sort="overall_initial">OVR start</button></th><th><button type="button" data-sort="overall_current">OVR current</button></th><th><button type="button" data-sort="potential_initial">POT start</button></th><th><button type="button" data-sort="potential_current">POT current</button></th><th><button type="button" data-sort="value_initial">Market value start</button></th><th><button type="button" data-sort="value_current">Market value current</button></th><th><button type="button" data-sort="status">Status</button></th><th><button type="button" data-sort="nationality_code">Nationality</button></th><th><button type="button" data-sort="birth_date">Birth date</button></th><th><span class="visually-hidden">Actions</span></th></tr></thead><tbody data-squad-rows>
<?php foreach ($players as $player): ?><tr data-squad-row data-url="<?= Html::encode($urlGenerator->generate('career.squad.update', ['id' => $career->id->toString(), 'playerId' => $player->id->toString()])) ?>"><td><select name="position"><?php foreach ($positions as $position): ?><option<?= $player->position->value === $position ? ' selected' : '' ?>><?= $position ?></option><?php endforeach ?></select></td><td><input name="name" value="<?= Html::encode($player->playerName) ?>"></td><td><output data-age></output></td><td><input name="overall_initial" type="number" min="1" max="99" value="<?= $player->overallInitial ?>"></td><td><input name="overall_current" type="number" min="1" max="99" placeholder="<?= $player->overallInitial ?>" value="<?= $player->overallFinal ?? '' ?>"></td><td><input name="potential_initial" type="number" min="1" max="99" value="<?= $player->potentialInitial ?>"></td><td><input name="potential_current" type="number" min="1" max="99" placeholder="<?= $player->potentialInitial ?>" value="<?= $player->potentialFinal ?? '' ?>"></td><td><input name="value_initial" inputmode="decimal" value="<?= Html::encode($player->valueInitial) ?>" data-money></td><td><input name="value_current" inputmode="decimal" placeholder="<?= Html::encode($player->valueInitial) ?>" value="<?= Html::encode($player->valueFinal ?? '') ?>" data-money></td><td><select name="status"><option value="Starter"<?= $player->status->value === 'Starter' ? ' selected' : '' ?>>Starter</option><option value="Substitute"<?= $player->status->value === 'Substitute' ? ' selected' : '' ?>>Substitute</option><option value="LoanedOut"<?= $player->status->value === 'LoanedOut' ? ' selected' : '' ?>>On loan</option><option value="Active"<?= $player->status->value === 'Active' ? ' selected' : '' ?>>Unassigned</option></select></td><td><input name="nationality_code" maxlength="2" value="<?= Html::encode($player->nationalityCode) ?>"></td><td><input name="birth_date" type="date" value="<?= Html::encode($player->birthDate->value) ?>"></td><td class="squad-row-actions"><form class="squad-row-delete" method="post" action="<?= Html::encode($urlGenerator->generate('career.squad.delete', ['id' => $career->id->toString(), 'playerId' => $player->id->toString()])) ?>" data-delete-squad-player><?= $csrf->hiddenInput()->render() ?><button type="submit" aria-label="Remove <?= Html::encode($player->playerName) ?>"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M10 11v6M14 11v6M9 7l1-2h4l1 2M7 7l1 13h8l1-13"/></svg></button></form></td></tr><?php endforeach ?>
<tr class="squad-table__new" data-new-row><td><select form="new-squad-player" name="position" required><option value=""></option><?php foreach ($positions as $position): ?><option><?= $position ?></option><?php endforeach ?></select></td><td><input form="new-squad-player" name="name" autocomplete="off" placeholder="New player" required></td><td><output data-age>—</output></td><td><input form="new-squad-player" name="overall" type="number" min="1" max="99" required></td><td>—</td><td><input form="new-squad-player" name="potential" type="number" min="1" max="99" required></td><td>—</td><td><input form="new-squad-player" name="value" inputmode="decimal" required data-money></td><td>—</td><td><select form="new-squad-player" name="status"><option value="Starter">Starter</option><option value="Substitute">Substitute</option><option value="LoanedOut">On loan</option></select></td><td><input form="new-squad-player" name="nationality_code" maxlength="2" placeholder="PT" required></td><td><input form="new-squad-player" name="birth_date" type="date" required></td><td></td></tr>
</tbody></table></div></section>
